version: "3.8"
services:
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: social_media
      MYSQL_USER: social_media_admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'